sudo : required
services:
  - docker:
  
before_install:
  - docker build -t 50350423/test -f ./client/dockerfile.dev ./client
  
script: 
  - docker run 50350423/test npm test -- --coverage
  
after success:
  - docker build -t 50350423/client ./client
  - docker build -t 50350423/nginx ./nginx
  - docker build -t 50350423/server ./server
  - docker build -t 50350423/worker ./worker
  - echo "$docker_mdp" | docker login -u "$dockerid" --password-stdin
  - docker push 50350423/client
  - docker push 50350423/nginx
  - docker push 50350423/server
  - docker push 50350423/worker