sudo : required
services:
  - docker:
  
before_install:
  - docker build -t travis/test -f ./client/dockerfile.dev ./client
  
script: 
  - docker run travis/test npm test -- --coverage
  
after success:
  - docker build -t travis/client ./client
  - docker build -t travis/nginx ./nginx
  - docker build -t travis/server ./server
  - docker build -t travis/worker ./worker
  - echo "$docker_mdp" | docker login -u "$dockerid" --password-stdin
  - docker push travis/client
  - docker push travis/nginx
  - docker push travis/server
  - docker push travis/worker